Repository boostcamp-2020/Project13-Web-Video-Editor, pull requests merged in 2020-11, with the labels that each got.

#2 [FE] 프론트 개발 환경 설정
  .eslintignore
  .eslintrc.js
  client/babel.config.js
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/atoms/index.tsx
  client/src/components/molecules/index.tsx
  client/src/components/organisms/index.tsx
  client/src/index.html
  client/src/index.tsx
  client/src/pages/index.tsx
  client/webpack.common.ts
  client/webpack.dev.ts
  client/webpack.prod.ts
  server/src/main/controllers/index.ts
  server/src/main/loaders/index.ts
  server/src/main/routes/index.ts
  server/src/main/services/index.ts
  tsconfig.json
Labels: ⚛️ REACT, 🌈 FE

#3 [COMMON] 프로젝트 초기 개발 환경 설정
  .eslintignore
  .eslintrc.js
  .github/PULL_REQUEST_TEMPLATE.md
  .gitmessage
  .prettierrc
  client/babel.config.js
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/atoms/index.tsx
  client/src/components/molecules/index.tsx
  client/src/components/organisms/index.tsx
  client/src/index.html
  client/src/index.tsx
  client/src/pages/index.tsx
  client/webpack.common.ts
  client/webpack.dev.ts
  client/webpack.prod.ts
  package-lock.json
  package.json
  server/bin/www.ts
  server/package-lock.json
  server/package.json
  server/src/main/App.ts
  server/src/main/controllers/index.ts
  server/src/main/loaders/index.ts
  server/src/main/routes/index.ts
  server/src/main/services/index.ts
  server/webpack.config.js
  tsconfig.json
Labels: 🌈 FE, 🛢 BE

#4 [COMMON] : [FIX] start 스크립트 및 import 수정
  client/package-lock.json
  client/package.json
  server/package.json
  server/src/main/App.ts
Labels: ☁️ DEPLOY, 🐞 BUG, 🔥 HOTFIX

#9 [FE] File Input component 구현
  .github/ISSUE_TEMPLATE/api.md
  .github/ISSUE_TEMPLATE/react-component.md
  .github/ISSUE_TEMPLATE/react-store.md
  README.md
  client/package-lock.json
  client/package.json
  client/src/components/atoms/FileInput/FileInput.tsx
  client/src/components/atoms/FileInput/index.ts
  server/package.json
  server/src/main/App.ts
Labels: ⚛️ REACT, 🌈 FE

#7 [BE] 비디오 ObjectStorage에 올리기
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  server/bin/www.ts
  server/package-lock.json
  server/package.json
  server/src/main/App.ts
  server/src/main/controllers/index.ts
  server/src/main/controllers/video.ts
  server/src/main/loaders/errorHandler.ts
  server/src/main/loaders/express.ts
  server/src/main/loaders/index.ts
  server/src/main/middlewares/multer.ts
  server/src/main/routes/index.ts
  server/src/main/routes/video.ts
  server/src/main/services/index.ts
  server/src/main/services/video.ts
  server/src/main/utils/handler.ts
Labels: 🌪 API, 🛢 BE

#17 [FE] Header Component 및 Store 구현
  .eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/atoms/Button/Button.tsx
  client/src/components/atoms/Button/index.ts
  client/src/components/atoms/Button/style.ts
  client/src/components/atoms/Canvas/Canvas.tsx
  client/src/components/atoms/Canvas/index.ts
  client/src/components/atoms/FileInput/FileInput.tsx
  client/src/components/atoms/Logo/Logo.tsx
  client/src/components/atoms/Logo/index.ts
  client/src/components/atoms/Video/Video.tsx
  client/src/components/atoms/Video/index.ts
  client/src/components/molecules/ButtonGroup/ButtonGroup.tsx
  client/src/components/molecules/ButtonGroup/index.ts
  client/src/components/molecules/UploadArea/UploadArea.tsx
  client/src/components/molecules/UploadArea/index.ts
  client/src/components/organisms/Header/Header.tsx
  client/src/components/organisms/Header/index.ts
  client/src/store/index.ts
  client/src/store/originalVideo/actionTypes.ts
  client/src/store/originalVideo/actions.ts
  client/src/store/originalVideo/reducer.ts
  client/src/store/originalVideo/sagas.ts
  client/src/store/reducer.ts
  client/src/store/sagas.ts
  client/src/theme/colors.tsx
  client/src/theme/globalStyle.tsx
  client/src/theme/sizes.ts
  server/src/main/routes/video.ts
Labels: ⚛️ REACT, 🌈 FE

#18 [FE] Webgl Controller 구현 및 적용
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/atoms/Video/Video.tsx
  client/src/index.html
  client/src/webgl/fragmentShaderSource.ts
  client/src/webgl/vertexShaderSource.ts
  client/src/webgl/webglController.ts
Labels: 🌈 FE, 🎆 WEBGL

#22 [FE] Thumbnail 구현 및 리팩토링, 스타일 추가
  .eslintrc.js
  client/src/App.tsx
  client/src/components/atoms/FileInput/FileInput.tsx
  client/src/components/atoms/Thumbnail/Thumbnail.tsx
  client/src/components/atoms/Thumbnail/index.ts
  client/src/components/atoms/Video/Video.tsx
  client/src/components/molecules/UploadArea/UploadArea.tsx
  client/src/components/organisms/Tools/Tools.tsx
  client/src/components/organisms/Tools/index.ts
  client/src/components/organisms/VideoContainer/VideoContainer.tsx
  client/src/components/organisms/VideoContainer/index.ts
  client/src/components/organisms/index.tsx
  client/src/theme/globalStyle.tsx
Labels: ⚛️ REACT, 🌈 FE

#23 [FE] 미사용 shader source 제거 및 타입 정의, 리팩토링
  client/src/webgl/fragmentShaderSource.ts
  client/src/webgl/vertexShaderSource.ts
  client/src/webgl/webglController.ts
Labels: 🌈 FE, 🎆 WEBGL

#25 [FE] Store 변경사항 반영 및 리팩토링
  .eslintrc.js
  client/src/App.tsx
  client/src/components/atoms/Thumbnail/Thumbnail.tsx
  client/src/components/atoms/Video/Video.tsx
  client/src/components/atoms/Video/index.ts
  client/src/components/atoms/index.tsx
  client/src/components/molecules/ButtonGroup/ButtonGroup.tsx
  client/src/components/molecules/UploadArea/UploadArea.tsx
  client/src/components/molecules/index.tsx
  client/src/components/organisms/Tools/Tools.tsx
  client/src/components/organisms/VideoContainer/VideoContainer.tsx
  client/src/store/originalVideo/actionTypes.ts
  client/src/store/originalVideo/actions.ts
  client/src/store/originalVideo/reducer.ts
  client/src/webgl/webglController.ts
  server/src/main/loaders/express.ts
Labels: ⚛️ REACT, 🌈 FE

#27 [FE] video class
  .eslintrc.js
  client/src/components/atoms/Thumbnail/Thumbnail.tsx
  client/src/components/molecules/UploadArea/UploadArea.tsx
  client/src/components/organisms/Tools/Tools.tsx
  client/src/video/index.tsx
  client/src/video/video.tsx
  client/src/webgl/webglController.ts
Labels: 🌈 FE

#28 [COMMON] 비동기 로직 saga로 리팩토링
  .eslintrc.js
  client/src/App.tsx
  client/src/api/index.ts
  client/src/api/video.ts
  client/src/components/atoms/Thumbnail/Thumbnail.tsx
  client/src/components/molecules/UploadArea/UploadArea.tsx
  client/src/components/organisms/Header/Header.tsx
  client/src/components/organisms/Tools/Tools.tsx
  client/src/store/index.ts
  client/src/store/originalVideo/actionTypes.ts
  client/src/store/originalVideo/actions.ts
  client/src/store/originalVideo/reducer.ts
  client/src/store/originalVideo/sagas.ts
  client/src/store/sagas.ts
  client/src/store/selectors.ts
  client/src/utils/error.ts
  client/src/webgl/webglController.ts
  server/src/main/controllers/video.ts
Labels: ⚛️ REACT, 🌈 FE, 🌪 API, 🛢 BE

#30 [FE] Video Play Tools 구현
  client/src/components/organisms/Tools/Tools.tsx
  client/src/video/video.tsx
Labels: ⚛️ REACT, 🌈 FE

#37 [FE] TimeLine, CurrentVideo Store, 취소 버튼 동작 구현
  client/src/App.tsx
  client/src/components/atoms/FileInput/FileInput.tsx
  client/src/components/atoms/Slider/Slider.tsx
  client/src/components/atoms/Slider/index.ts
  client/src/components/atoms/Thumbnail/Thumbnail.tsx
  client/src/components/atoms/TimeText/TimeText.tsx
  client/src/components/atoms/TimeText/index.ts
  client/src/components/molecules/CurrentTime/CurrentTime.tsx
  client/src/components/molecules/CurrentTime/index.ts
  client/src/components/molecules/TimeZone/TimeZone.tsx
  client/src/components/molecules/TimeZone/index.ts
  client/src/components/molecules/UploadArea/UploadArea.tsx
  client/src/components/organisms/Header/Header.tsx
  client/src/components/organisms/TimeLine/TimeLine.tsx
  client/src/components/organisms/TimeLine/index.ts
  client/src/components/organisms/Tools/Tools.tsx
  client/src/store/actionTypes.ts
  client/src/store/currentVideo/actions.ts
  client/src/store/currentVideo/reducer.ts
  client/src/store/originalVideo/actionTypes.ts
  client/src/store/originalVideo/actions.ts
  client/src/store/originalVideo/reducer.ts
  client/src/store/originalVideo/sagas.ts
  client/src/store/reducer.ts
  client/src/store/sagas.ts
  client/src/store/selectors.ts
  client/src/theme/colors.tsx
  client/src/utils/time.ts
  client/src/video/video.tsx
  client/src/webgl/webglController.ts
Labels: ⚛️ REACT, 🌈 FE

#40 [FE] Slider 이동 및 HoverSlider 구현
  client/src/components/atoms/HoverSlider/HoverSlider.tsx
  client/src/components/atoms/HoverSlider/index.ts
  client/src/components/atoms/Slider/Slider.tsx
  client/src/components/molecules/Thumbnail/Thumbnail.tsx
  client/src/components/molecules/Thumbnail/index.ts
  client/src/components/organisms/TimeLine/TimeLine.tsx
  client/src/components/organisms/Tools/Tools.tsx
  client/src/store/currentVideo/actions.ts
  client/src/store/currentVideo/reducer.ts
  client/src/store/originalVideo/actions.ts
  client/src/store/selectors.ts
Labels: ⚛️ REACT, 🌈 FE

#41 [FE] CropLayer구현
  client/package-lock.json
  client/package.json
  client/src/components/molecules/CropLayer/CropLayer.tsx
  client/src/components/molecules/CropLayer/index.ts
  client/src/components/molecules/Thumbnail/Thumbnail.tsx
  client/src/components/organisms/Tools/Tools.tsx
  client/src/theme/colors.tsx
  client/src/utils/convert.ts
Labels: ⚛️ REACT, 🌈 FE

#43 [FE] 로딩중 애니메이션 구현 및 썸네일 리팩토링
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/atoms/Loading/Loading.tsx
  client/src/components/atoms/Loading/index.ts
  client/src/components/molecules/ButtonGroup/ButtonGroup.tsx
  client/src/components/molecules/CropLayer/CropLayer.tsx
  client/src/components/molecules/Thumbnail/Thumbnail.tsx
  client/src/components/organisms/Tools/Tools.tsx
  client/src/index.tsx
  client/src/store/currentVideo/actions.ts
  client/src/store/originalVideo/actions.ts
  client/src/store/originalVideo/reducer.ts
  client/src/store/originalVideo/sagas.ts
  client/src/store/selectors.ts
  client/src/theme/sizes.ts
  client/src/video/video.tsx
Labels: ⚛️ REACT, 🌈 FE, 🛠REFACTOR

#46 [FE] favicon 설정 및 dropdown 애니메이션 추가
  client/src/components/atoms/FileInput/FileInput.tsx
  client/src/index.html
Labels: ⚛️ REACT, 🌈 FE

#47 [FE] 취소 버튼 동작 구현 및 리팩토링
  client/src/components/atoms/Slider/Slider.tsx
  client/src/components/molecules/CurrentTime/CurrentTime.tsx
  client/src/components/molecules/Thumbnail/Thumbnail.tsx
  client/src/components/molecules/UploadArea/UploadArea.tsx
  client/src/components/organisms/Tools/Tools.tsx
  client/src/components/organisms/VideoContainer/VideoContainer.tsx
  client/src/index.html
  client/src/store/originalVideo/sagas.ts
  client/src/store/sagas.ts
  client/src/video/video.tsx
  client/src/webgl/webglController.ts
  tsconfig.json
Labels: ⚛️ REACT, 🌈 FE
