Repository boostcamp-2020/Project13-Web-Video-Editor, pull requests merged in 2020-12, with the labels that each got.

#50 [FE] Tools 버튼 그룹 구현 / Crop store 등록
  client/src/App.tsx
  client/src/components/molecules/CropLayer/CropLayer.tsx
  client/src/components/molecules/Thumbnail/Thumbnail.tsx
  client/src/components/organisms/Tools/Tools.tsx
  client/src/components/organisms/Tools/buttonData.tsx
  client/src/components/organisms/Tools/reducer.tsx
  client/src/components/organisms/VideoContainer/VideoContainer.tsx
  client/src/pages/edit.tsx
  client/src/pages/index.tsx
  client/src/store/actionTypes.ts
  client/src/store/crop/actions.ts
  client/src/store/crop/reducer.ts
  client/src/store/reducer.ts
  client/src/store/selectors.ts
Labels: ⚛️ REACT, 🌈 FE

#51 [FE] Crop 이후 Thumbnail Update 구현
  client/src/components/molecules/TimeZone/TimeZone.tsx
  client/src/store/crop/actions.ts
  client/src/store/crop/reducer.ts
  client/src/store/crop/sagas.ts
  client/src/store/currentVideo/actions.ts
  client/src/store/sagas.ts
  client/src/store/selectors.ts
  client/src/video/video.tsx
Labels: ⚛️ REACT, 🌈 FE

#53 [FE] Crop 이후 slider / currentTime 로직 수정 및 오류 수정
  client/src/components/atoms/Slider/Slider.tsx
  client/src/components/molecules/CurrentTime/CurrentTime.tsx
  client/src/components/molecules/Thumbnail/Thumbnail.tsx
  client/src/components/organisms/Tools/Tools.tsx
  client/src/store/originalVideo/actions.ts
  client/src/store/originalVideo/reducer.ts
Labels: ⚛️ REACT, 🌈 FE

#55 [FE] 비디오 유무에 따른 버튼 클릭
  client/src/components/atoms/Button/Button.tsx
  client/src/components/molecules/ButtonGroup/ButtonGroup.tsx
  client/src/components/organisms/Header/Header.tsx
  client/src/components/organisms/Tools/Tools.tsx
  client/src/components/organisms/Tools/buttonData.tsx
Labels: ⚛️ REACT, 🌈 FE

#57 [BE] Video 목록 조회 API 및 Upload 결과 저장
  client/src/components/molecules/UploadArea/UploadArea.tsx
  server/package-lock.json
  server/package.json
  server/src/main/controllers/video.ts
  server/src/main/model/config.ts
  server/src/main/model/query.ts
  server/src/main/model/video.ts
  server/src/main/routes/index.ts
  server/src/main/routes/video.ts
  server/src/main/services/video.ts
Labels: 🌪 API, 🛢 BE

#61 [COMMON] User, Video Store구현, Modal 구현 및 리팩토링
  client/src/api/video.ts
  client/src/components/atoms/Canvas/Canvas.tsx
  client/src/components/atoms/Canvas/index.ts
  client/src/components/atoms/TimeText/TimeText.tsx
  client/src/components/atoms/VideoList/VideoItem.tsx
  client/src/components/atoms/VideoList/VideoList.tsx
  client/src/components/atoms/VideoList/index.ts
  client/src/components/molecules/CurrentTime/CurrentTime.tsx
  client/src/components/molecules/FileInput/FileInput.tsx
  client/src/components/molecules/FileInput/index.ts
  client/src/components/molecules/HoverSlider/HoverSlider.tsx
  client/src/components/molecules/HoverSlider/index.ts
  client/src/components/molecules/Modal/Modal.tsx
  client/src/components/molecules/Modal/index.ts
  client/src/components/molecules/Thumbnail/Thumbnail.tsx
  client/src/components/molecules/UploadArea/UploadArea.tsx
  client/src/components/organisms/Header/Header.tsx
  client/src/components/organisms/Tools/Tools.tsx
  client/src/store/actionTypes.ts
  client/src/store/crop/actions.ts
  client/src/store/crop/sagas.ts
  client/src/store/originalVideo/actions.ts
  client/src/store/originalVideo/reducer.ts
  client/src/store/originalVideo/sagas.ts
  client/src/store/reducer.ts
  client/src/store/sagas.ts
  client/src/store/selectors.ts
  client/src/store/user/actions.ts
  client/src/store/user/reducer.ts
  client/src/store/video/actions.ts
  client/src/store/video/reducer.ts
  client/src/store/video/sagas.ts
  client/src/theme/colors.tsx
  client/src/utils/time.ts
  client/src/webgl/webglController.ts
  server/src/main/model/query.ts
  server/src/main/model/video.ts
  server/src/main/services/video.ts
Labels: ⚛️ REACT, 🌈 FE, 🌪 API, 🛢 BE

#62 [FE] 전체적인 UI 개선작업
  client/src/components/atoms/Button/Button.tsx
  client/src/components/atoms/Button/index.ts
  client/src/components/atoms/Button/style.ts
  client/src/components/atoms/VideoList/VideoItem.tsx
  client/src/components/molecules/ButtonGroup/ButtonGroup.tsx
  client/src/components/molecules/FileInput/FileInput.tsx
  client/src/components/molecules/Modal/Modal.tsx
  client/src/components/molecules/UploadArea/UploadArea.tsx
  client/src/components/organisms/Header/Header.tsx
  client/src/components/organisms/TimeLine/TimeLine.tsx
  client/src/components/organisms/Tools/Tools.tsx
  client/src/components/organisms/Tools/buttonData.tsx
  client/src/components/organisms/VideoContainer/VideoContainer.tsx
  client/src/pages/edit.tsx
  client/src/theme/colors.tsx
Labels: ⚛️ REACT, 🌈 FE

#63 [COMMON] 3주차 데모 버전
  client/src/api/video.ts
  client/src/components/atoms/Button/Button.tsx
  client/src/components/atoms/Button/index.ts
  client/src/components/atoms/Button/style.ts
  client/src/components/atoms/Canvas/Canvas.tsx
  client/src/components/atoms/Canvas/index.ts
  client/src/components/atoms/Slider/Slider.tsx
  client/src/components/atoms/TimeText/TimeText.tsx
  client/src/components/atoms/VideoList/VideoItem.tsx
  client/src/components/atoms/VideoList/VideoList.tsx
  client/src/components/atoms/VideoList/index.ts
  client/src/components/molecules/ButtonGroup/ButtonGroup.tsx
  client/src/components/molecules/CurrentTime/CurrentTime.tsx
  client/src/components/molecules/FileInput/FileInput.tsx
  client/src/components/molecules/FileInput/index.ts
  client/src/components/molecules/HoverSlider/HoverSlider.tsx
  client/src/components/molecules/HoverSlider/index.ts
  client/src/components/molecules/Modal/Modal.tsx
  client/src/components/molecules/Modal/index.ts
  client/src/components/molecules/Thumbnail/Thumbnail.tsx
  client/src/components/molecules/UploadArea/UploadArea.tsx
  client/src/components/organisms/Header/Header.tsx
  client/src/components/organisms/TimeLine/TimeLine.tsx
  client/src/components/organisms/Tools/Tools.tsx
  client/src/components/organisms/Tools/buttonData.tsx
  client/src/components/organisms/VideoContainer/VideoContainer.tsx
  client/src/pages/edit.tsx
  client/src/store/actionTypes.ts
  client/src/store/crop/actions.ts
  client/src/store/crop/sagas.ts
  client/src/store/originalVideo/actions.ts
  client/src/store/originalVideo/reducer.ts
  client/src/store/originalVideo/sagas.ts
  client/src/store/reducer.ts
  client/src/store/sagas.ts
  client/src/store/selectors.ts
  client/src/store/user/actions.ts
  client/src/store/user/reducer.ts
  client/src/store/video/actions.ts
  client/src/store/video/reducer.ts
  client/src/store/video/sagas.ts
  client/src/theme/colors.tsx
  client/src/utils/time.ts
  client/src/webgl/webglController.ts
  server/package-lock.json
  server/package.json
  server/src/main/controllers/video.ts
  server/src/main/model/config.ts
  server/src/main/model/query.ts
  server/src/main/model/video.ts
  server/src/main/routes/index.ts
  server/src/main/routes/video.ts
  server/src/main/services/video.ts
Labels: ☁️ DEPLOY

#64 [COMMON] 버전 0.0.2 핫픽스
  .gitignore
  client/src/App.tsx
  client/src/api/index.ts
  server/bin/www.ts
  server/package-lock.json
  server/package.json
  server/src/main/model/config.ts
  server/src/main/services/video.ts
Labels: 🔥 HOTFIX

#65 [COMMON] 버전 0.0.2 핫픽스
  .github/ISSUE_TEMPLATE/api.md
  .github/ISSUE_TEMPLATE/react-component.md
  .github/ISSUE_TEMPLATE/react-store.md
  .gitignore
  README.md
  client/src/App.tsx
  client/src/api/index.ts
  server/bin/www.ts
  server/package-lock.json
  server/package.json
  server/src/main/model/config.ts
  server/src/main/services/video.ts
Labels: 🔥 HOTFIX

#68 [FE] 각종 버그 수정 및 최적화
  client/src/components/atoms/Slider/Slider.tsx
  client/src/components/molecules/CropLayer/CropLayer.tsx
  client/src/components/molecules/CurrentTime/CurrentTime.tsx
  client/src/components/molecules/HoverSlider/HoverSlider.tsx
  client/src/components/molecules/Thumbnail/Thumbnail.tsx
  client/src/components/molecules/TimeZone/TimeZone.tsx
  client/src/store/crop/sagas.ts
  client/src/video/video.tsx
Labels: ⚛️ REACT, 🌈 FE, 🐞 BUG

#69 [FE] video 회전, 변경 시 해상도 문제 해결 및 서명기능 추가
  client/src/components/organisms/Tools/Tools.tsx
  client/src/components/organisms/Tools/buttonData.tsx
  client/src/components/organisms/Tools/reducer.tsx
  client/src/webgl/webglController.ts
Labels: ⚛️ REACT, 🌈 FE, 🎆 WEBGL

#70 [FE] History store구현 및 로딩화면 수정
  client/src/components/atoms/Loading/Loading.tsx
  client/src/components/molecules/CropLayer/CropLayer.tsx
  client/src/components/molecules/CurrentTime/CurrentTime.tsx
  client/src/components/molecules/TimeZone/TimeZone.tsx
  client/src/components/organisms/Header/Header.tsx
  client/src/components/organisms/Tools/Tools.tsx
  client/src/store/actionTypes.ts
  client/src/store/crop/sagas.ts
  client/src/store/currentVideo/actions.ts
  client/src/store/currentVideo/reducer.ts
  client/src/store/history/actions.ts
  client/src/store/history/reducer.ts
  client/src/store/history/sagas.ts
  client/src/store/originalVideo/sagas.ts
  client/src/store/reducer.ts
  client/src/store/sagas.ts
  client/src/store/selectors.ts
  client/src/theme/colors.tsx
  client/src/webgl/webglController.ts
Labels: ⚛️ REACT, 🌈 FE

#74 [FE] Thumbnail 동기화 및 서버에서 영상 다운로드 구현
  client/src/api/video.ts
  client/src/components/atoms/Button/Button.tsx
  client/src/components/atoms/ModalComponent/TextInput.tsx
  client/src/components/atoms/ModalComponent/VideoItem.tsx
  client/src/components/atoms/ModalComponent/VideoList.tsx
  client/src/components/atoms/ModalComponent/index.ts
  client/src/components/atoms/ModalComponent/props.ts
  client/src/components/atoms/Slider/Slider.tsx
  client/src/components/atoms/VideoList/index.ts
  client/src/components/molecules/FileInput/FileInput.tsx
  client/src/components/molecules/HoverSlider/HoverSlider.tsx
  client/src/components/molecules/Modal/Modal.tsx
  client/src/components/molecules/Thumbnail/Thumbnail.tsx
  client/src/components/organisms/Header/Header.tsx
  client/src/components/organisms/Tools/Tools.tsx
  client/src/pages/edit.tsx
  client/src/store/actionTypes.ts
  client/src/store/history/actions.ts
  client/src/store/history/reducer.ts
  client/src/store/history/sagas.ts
  client/src/store/originalVideo/actions.ts
  client/src/store/originalVideo/sagas.ts
  client/src/store/sagas.ts
  client/src/store/selectors.ts
  server/bin/www.ts
Labels: ⚛️ REACT, 🌈 FE, 🐞 BUG, 🛠REFACTOR

#75 [FE] mp4-h264를 활용한 영상 인코딩 및 서명 기능 및 각종 오류 수정
  client/package-lock.json
  client/package.json
  client/src/components/atoms/ModalComponent/VideoList.tsx
  client/src/components/atoms/Range/Range.tsx
  client/src/components/atoms/Range/index.ts
  client/src/components/molecules/CropLayer/CropLayer.tsx
  client/src/components/molecules/FileInput/FileInput.tsx
  client/src/components/molecules/Thumbnail/Thumbnail.tsx
  client/src/components/organisms/Tools/Tools.tsx
  client/src/components/organisms/Tools/reducer.tsx
  client/src/store/history/actions.ts
  client/src/store/history/sagas.ts
  client/src/store/originalVideo/actions.ts
  client/src/store/originalVideo/sagas.ts
  client/src/theme/globalStyle.tsx
  client/src/video/encoding.ts
  client/src/webgl/webglConfig.ts
  client/src/webgl/webglController.ts
  client/webpack.common.ts
  server/webpack.config.js
Labels: ⚛️ REACT, 🌈 FE, 🎆 WEBGL, 🐞 BUG

#76 [COMMON] 0.0.3 버전 배포
  client/package-lock.json
  client/package.json
  client/src/api/video.ts
  client/src/components/atoms/Button/Button.tsx
  client/src/components/atoms/Loading/Loading.tsx
  client/src/components/atoms/ModalComponent/TextInput.tsx
  client/src/components/atoms/ModalComponent/VideoItem.tsx
  client/src/components/atoms/ModalComponent/VideoList.tsx
  client/src/components/atoms/ModalComponent/index.ts
  client/src/components/atoms/ModalComponent/props.ts
  client/src/components/atoms/Range/Range.tsx
  client/src/components/atoms/Range/index.ts
  client/src/components/atoms/Slider/Slider.tsx
  client/src/components/atoms/VideoList/index.ts
  client/src/components/molecules/CropLayer/CropLayer.tsx
  client/src/components/molecules/CurrentTime/CurrentTime.tsx
  client/src/components/molecules/FileInput/FileInput.tsx
  client/src/components/molecules/HoverSlider/HoverSlider.tsx
  client/src/components/molecules/Modal/Modal.tsx
  client/src/components/molecules/Thumbnail/Thumbnail.tsx
  client/src/components/molecules/TimeZone/TimeZone.tsx
  client/src/components/organisms/Header/Header.tsx
  client/src/components/organisms/Tools/Tools.tsx
  client/src/components/organisms/Tools/buttonData.tsx
  client/src/components/organisms/Tools/reducer.tsx
  client/src/pages/edit.tsx
  client/src/store/actionTypes.ts
  client/src/store/crop/sagas.ts
  client/src/store/currentVideo/actions.ts
  client/src/store/currentVideo/reducer.ts
  client/src/store/history/actions.ts
  client/src/store/history/reducer.ts
  client/src/store/history/sagas.ts
  client/src/store/originalVideo/actions.ts
  client/src/store/originalVideo/sagas.ts
  client/src/store/reducer.ts
  client/src/store/sagas.ts
  client/src/store/selectors.ts
  client/src/theme/colors.tsx
  client/src/theme/globalStyle.tsx
  client/src/video/encoding.ts
  client/src/video/video.tsx
  client/src/webgl/webglConfig.ts
  client/src/webgl/webglController.ts
  client/webpack.common.ts
  server/bin/www.ts
  server/webpack.config.js
Labels: ☁️ DEPLOY

#77 [FE] 각종 오류 수정
  client/src/components/molecules/CurrentTime/CurrentTime.tsx
  client/src/components/organisms/Tools/Tools.tsx
  client/src/store/crop/actions.ts
  client/src/store/crop/reducer.ts
  client/src/store/currentVideo/reducer.ts
  client/src/store/selectors.ts
Labels: ⚛️ REACT, 🌈 FE, 🐞 BUG

#78 [FE] 오디오 mux 구현 및 frame 보존 작업
  client/package-lock.json
  client/package.json
  client/src/components/atoms/Button/Button.tsx
  client/src/components/atoms/Button/index.ts
  client/src/components/atoms/Button/style.ts
  client/src/store/crop/sagas.ts
  client/src/store/originalVideo/sagas.ts
  client/src/video/encoding.ts
  client/src/video/index.tsx
  client/src/video/mux.ts
Labels: ⚛️ REACT, 🌈 FE

#80 [FE] 비디오 필터 효과 구현
  client/src/components/atoms/Button/Button.tsx
  client/src/components/atoms/VolumeRange/VolumeRange.tsx
  client/src/components/atoms/VolumeRange/index.ts
  client/src/components/molecules/ButtonGroup/ButtonGroup.tsx
  client/src/components/molecules/EffectSliders/EffectSliders.tsx
  client/src/components/molecules/EffectSliders/Range.tsx
  client/src/components/molecules/EffectSliders/index.ts
  client/src/components/molecules/Thumbnail/Thumbnail.tsx
  client/src/components/organisms/Tools/Tools.tsx
  client/src/components/organisms/Tools/buttonData.tsx
  client/src/components/organisms/Tools/reducer.tsx
  client/src/store/actionTypes.ts
  client/src/store/currentVideo/actions.ts
  client/src/store/currentVideo/reducer.ts
  client/src/store/history/actions.ts
  client/src/store/history/reducer.ts
  client/src/store/selectors.ts
  client/src/theme/colors.tsx
  client/src/video/encoding.ts
  client/src/video/video.tsx
  client/src/webgl/fragmentShaderSource.ts
  client/src/webgl/webglController.ts
Labels: ⚛️ REACT, 🌈 FE, 🎆 WEBGL

#83 [COMMON] 각종 오류 수정 및 비율 조정 기능 추가
  client/package-lock.json
  client/package.json
  client/src/components/atoms/Encoding/Encoding.tsx
  client/src/components/atoms/Encoding/index.ts
  client/src/components/atoms/Loading/Loading.tsx
  client/src/components/atoms/VolumeRange/VolumeRange.tsx
  client/src/components/molecules/EffectSliders/EffectSliders.tsx
  client/src/components/molecules/EffectSliders/Range.tsx
  client/src/components/molecules/Thumbnail/Thumbnail.tsx
  client/src/components/organisms/Tools/Tools.tsx
  client/src/components/organisms/Tools/reducer.tsx
  client/src/components/organisms/VideoContainer/VideoContainer.tsx
  client/src/pages/edit.tsx
  client/src/store/actionTypes.ts
  client/src/store/history/actions.ts
  client/src/store/history/reducer.ts
  client/src/store/history/sagas.ts
  client/src/store/originalVideo/actions.ts
  client/src/store/originalVideo/reducer.ts
  client/src/store/originalVideo/sagas.ts
  client/src/store/selectors.ts
  client/src/store/video/reducer.ts
  client/src/video/metadata.ts
  client/src/webgl/webglConfig.ts
  client/src/webgl/webglController.ts
  client/webpack.common.ts
  server/src/main/controllers/video.ts
  server/src/main/model/query.ts
  server/src/main/model/video.ts
  server/src/main/services/video.ts
Labels: ⚛️ REACT, 🌈 FE, 🐞 BUG, 🛠REFACTOR, 🛢 BE

#84 [FE] 도움말 추가 및 해상도 조절
  client/src/components/atoms/Encoding/Encoding.tsx
  client/src/components/atoms/ModalComponent/Help.tsx
  client/src/components/atoms/ModalComponent/TextInput.tsx
  client/src/components/atoms/ModalComponent/index.ts
  client/src/components/organisms/Header/Header.tsx
  client/src/store/crop/sagas.ts
  client/src/theme/globalStyle.tsx
  client/src/video/encoding.ts
  client/src/video/video.tsx
  client/src/webgl/webglController.ts
Labels: ⚛️ REACT, 🌈 FE, 🎆 WEBGL, 🐞 BUG, 🛠REFACTOR

#85 [COMMON] 5주차 데모버전 배포
  client/package-lock.json
  client/package.json
  client/src/components/atoms/Button/Button.tsx
  client/src/components/atoms/Button/index.ts
  client/src/components/atoms/Button/style.ts
  client/src/components/atoms/Encoding/Encoding.tsx
  client/src/components/atoms/Encoding/index.ts
  client/src/components/atoms/Loading/Loading.tsx
  client/src/components/atoms/ModalComponent/Help.tsx
  client/src/components/atoms/ModalComponent/TextInput.tsx
  client/src/components/atoms/ModalComponent/index.ts
  client/src/components/atoms/VolumeRange/VolumeRange.tsx
  client/src/components/atoms/VolumeRange/index.ts
  client/src/components/molecules/ButtonGroup/ButtonGroup.tsx
  client/src/components/molecules/CurrentTime/CurrentTime.tsx
  client/src/components/molecules/EffectSliders/EffectSliders.tsx
  client/src/components/molecules/EffectSliders/Range.tsx
  client/src/components/molecules/EffectSliders/index.ts
  client/src/components/molecules/Thumbnail/Thumbnail.tsx
  client/src/components/organisms/Header/Header.tsx
  client/src/components/organisms/Tools/Tools.tsx
  client/src/components/organisms/Tools/buttonData.tsx
  client/src/components/organisms/Tools/reducer.tsx
  client/src/components/organisms/VideoContainer/VideoContainer.tsx
  client/src/pages/edit.tsx
  client/src/store/actionTypes.ts
  client/src/store/crop/actions.ts
  client/src/store/crop/reducer.ts
  client/src/store/crop/sagas.ts
  client/src/store/currentVideo/actions.ts
  client/src/store/currentVideo/reducer.ts
  client/src/store/history/actions.ts
  client/src/store/history/reducer.ts
  client/src/store/history/sagas.ts
  client/src/store/originalVideo/actions.ts
  client/src/store/originalVideo/reducer.ts
  client/src/store/originalVideo/sagas.ts
  client/src/store/selectors.ts
  client/src/store/video/reducer.ts
  client/src/theme/colors.tsx
  client/src/theme/globalStyle.tsx
  client/src/video/encoding.ts
  client/src/video/index.tsx
  client/src/video/metadata.ts
  client/src/video/mux.ts
  client/src/video/video.tsx
  client/src/webgl/fragmentShaderSource.ts
  client/src/webgl/webglConfig.ts
  client/src/webgl/webglController.ts
  client/webpack.common.ts
  server/src/main/controllers/video.ts
  server/src/main/model/query.ts
  server/src/main/model/video.ts
  server/src/main/services/video.ts
Labels: ☁️ DEPLOY

#86 [FE] : [HOTFIX] 돌아간 영상 sign 핫픽스
  client/src/store/originalVideo/sagas.ts
  client/src/video/mux.ts
  client/src/video/video.tsx
  client/src/webgl/webglController.ts
  server/src/main/services/video.ts
Labels: 🔥 HOTFIX

#87 Hotfix
  client/src/components/atoms/Encoding/Encoding.tsx
  client/src/components/atoms/ModalComponent/Help.tsx
  client/src/video/video.tsx
  server/src/main/services/video.ts
Labels: 🌈 FE, 🐞 BUG, 🔥 HOTFIX, 🛢 BE

#88 Hotfix
  README.md
  client/src/components/atoms/Encoding/Encoding.tsx
  client/src/components/atoms/ModalComponent/Help.tsx
  client/src/video/video.tsx
  server/src/main/services/video.ts
Labels: 🔥 HOTFIX

#89 [COMMON] 다운로드 버튼 구현 및 한글화
  client/src/components/atoms/ModalComponent/VideoItem.tsx
  client/src/components/atoms/ModalComponent/VideoList.tsx
  client/src/components/molecules/FileInput/FileInput.tsx
  client/src/utils/time.ts
  server/package-lock.json
  server/package.json
  server/src/main/services/video.ts
Labels: 🌈 FE, 🔥 HOTFIX, 🛢 BE

#90 [COMMON] 다운로드 버튼 구현 및 한글화
  README.md
  client/src/components/atoms/ModalComponent/VideoItem.tsx
  client/src/components/atoms/ModalComponent/VideoList.tsx
  client/src/components/molecules/FileInput/FileInput.tsx
  client/src/utils/time.ts
  server/package-lock.json
  server/package.json
  server/src/main/services/video.ts
Labels: 🌈 FE, 🔥 HOTFIX, 🛢 BE
